# site settings
title: Cindy Alifia Putri
subtitle: Data Expert
email: cindyalifia39@gmail.com
description: Data Expert
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Bojonegoro
state: 
zip_code: 
country: Indonesia
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

collections:
  portfolio:
    output: true

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
